### ISSUE TITLE
Make port easily configurable

### ISSUE THREAD

**Issue by m-iancu** [aoripov/MEP#1]
Apparently, in scalatra, this is not completely trivial. It's needed for deploying since port 8080 is typically taken.

**Comment by aoripov** [comment]
[Jetty](http://www.eclipse.org/jetty/) - Java based http web server runs on port:8080 by default, so I added package [xsbt-web-plugin](https://github.com/earldouglas/xsbt-web-plugin) to allow easy change of port. To change the port you just need to change value of `myPort` variable in `MEP/build.sbt`. Now, it is running by default on port `9090`.

**Comment by m-iancu** [comment]
Excellent.
